name: Generate Secret

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch: # allow manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Keep credentials so git push works
        # persist-credentials defaults to true

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Run secret generator
        run: |
          nix run . --extra-experimental-features nix-command --extra-experimental-features flakes

      - name: Commit and push changes
        run: |
          git config --global user.name "secret-bot"
          git config --global user.email "secret-bot@secret.ai"
          git add .
          git commit -m "chore: daily secret update" || echo "No changes to commit"
          git push
